# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7wF_lgn21-mOaJz7JjXSYaOR_yueu9b
"""

import pandas as pd
import openpyxl

original_File = "xlsxFileName.xlsx"
row_per_file = 10000
df = pd.read_excel(original_File)
file_number = 1
initial_line = 1

for indice_bloco in range(0, len(df), row_per_file):
    bloco_df = df[indice_bloco:indice_bloco + row_per_file]
    bloco_df = bloco_df.dropna(how='all')
    bloco_df = bloco_df.reset_index(drop=True)
    wb_novo = openpyxl.Workbook()
    new_xlsx = wb_novo.active

    for coluna in range(1, len(bloco_df.columns) + 1):
        for linha in range(1, len(bloco_df) + 1):
            new_cell = new_xlsx.cell(row=linha, column=coluna)
            new_cell.value = bloco_df.iloc[linha - 1, coluna - 1]

    new_file_name = f"numerosSalvos{file_number}.xlsx"
    wb_novo.save(new_file_name)
    file_number += 1
    initial_line += row_per_file

if initial_line <= len(df):
    bloco_df = df[initial_line:]
    bloco_df = bloco_df.dropna(how='all')
    bloco_df = bloco_df.reset_index(drop=True)
    wb_novo = openpyxl.Workbook()
    new_file = wb_novo.active
    for coluna in range(1, len(bloco_df.columns) + 1):
        for linha in range(1, len(bloco_df) + 1):
            new_cell = new_xlsx.cell(row=linha, column=coluna)
            new_cell.value = bloco_df.iloc[linha - 1, coluna - 1]

    new_file_name = f"numerosSalvos{file_number}.xlsx"
    wb_novo.save(new_file_name)